# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^tuf/api/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        # TODO: configure args in pyproject.toml (see #1161)
        args: [--line-length=80, tuf/api]

  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
         # TODO: configure args in pyproject.toml (see #1161)
        args: [--line-length=80, --profile=black, tuf/api]
